
//! Autogenerated weights for `pallet_eterra_monte_carlo_ai`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_monte_carlo_ai
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-monte-carlo-ai/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_monte_carlo_ai`.
pub trait WeightInfo {
	fn suggest_move() -> Weight;
}

impl WeightInfo for () {
	fn suggest_move() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_monte_carlo_ai`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraMonteCarloAi::Nonce` (r:1 w:1)
	/// Proof: `EterraMonteCarloAi::Nonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn suggest_move() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1493`
		// Minimum execution time: 2_942_000_000 picoseconds.
		Weight::from_parts(3_136_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
