
//! Autogenerated weights for `pallet_eterra_simple_matchmaker`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_simple_matchmaker
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-simple-matchmaker/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_simple_matchmaker`.
pub trait WeightInfo {
	fn join_queue() -> Weight;
	fn leave_queue() -> Weight;
	fn process_queue() -> Weight;
}

impl WeightInfo for () {
	fn join_queue() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn leave_queue() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn process_queue() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_simple_matchmaker`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraSimpleMatchMaker::InQueue` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::InQueue` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Head` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::Head` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Tail` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::Tail` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::LiveSize` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::LiveSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Ring` (r:0 w:1)
	/// Proof: `EterraSimpleMatchMaker::Ring` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn join_queue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3513`
		// Minimum execution time: 448_000_000 picoseconds.
		Weight::from_parts(502_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `EterraSimpleMatchMaker::InQueue` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::InQueue` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::LiveSize` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::LiveSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn leave_queue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3513`
		// Minimum execution time: 242_000_000 picoseconds.
		Weight::from_parts(274_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraSimpleMatchMaker::LiveSize` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::LiveSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Head` (r:1 w:1)
	/// Proof: `EterraSimpleMatchMaker::Head` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Tail` (r:1 w:0)
	/// Proof: `EterraSimpleMatchMaker::Tail` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::Ring` (r:2 w:2)
	/// Proof: `EterraSimpleMatchMaker::Ring` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleMatchMaker::InQueue` (r:2 w:2)
	/// Proof: `EterraSimpleMatchMaker::InQueue` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::CurrentHandOf` (r:1 w:0)
	/// Proof: `Eterra::CurrentHandOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn process_queue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `348`
		//  Estimated: `6044`
		// Minimum execution time: 942_000_000 picoseconds.
		Weight::from_parts(1_004_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}
