
//! Autogenerated weights for `pallet_eterra_economy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-05-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-eterra-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_economy
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-economy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_economy`.
pub trait WeightInfo {
	fn create_product() -> Weight;
	fn set_product_status() -> Weight;
	fn grant_entitlement() -> Weight;
	fn revoke_entitlement() -> Weight;
	fn grant_credit() -> Weight;
	fn consume_credit() -> Weight;
	fn deposit_sponsor_funds() -> Weight;
	fn record_revenue() -> Weight;
	fn fulfill_product() -> Weight;
	fn claim_arcade_credit() -> Weight;
	fn set_ticket_asset() -> Weight;
	fn set_ticket_reward_policy() -> Weight;
	fn set_arcade_economy_pause() -> Weight;
	fn set_arcade_account_restriction() -> Weight;
	fn transfer_tickets() -> Weight;
	fn upsert_prize_sku() -> Weight;
	fn set_featured_rotation_config() -> Weight;
	fn redeem_prize_with_tickets() -> Weight;
	fn purchase_prize_with_native() -> Weight;
	fn upsert_arcade_pack_credit_sku_v2() -> Weight;
	fn redeem_arcade_pack_credit_with_tickets_v2() -> Weight;
	fn rotate_featured() -> Weight;
}

impl WeightInfo for () {
	fn create_product() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_product_status() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn grant_entitlement() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn revoke_entitlement() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn grant_credit() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn consume_credit() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn deposit_sponsor_funds() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn record_revenue() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn fulfill_product() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn claim_arcade_credit() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_ticket_asset() -> Weight { Weight::from_parts(20_000, 0) }
	fn set_ticket_reward_policy() -> Weight { Weight::from_parts(30_000, 0) }
	fn set_arcade_economy_pause() -> Weight { Weight::from_parts(15_000, 0) }
	fn set_arcade_account_restriction() -> Weight { Weight::from_parts(15_000, 0) }
	fn transfer_tickets() -> Weight { Weight::from_parts(50_000, 0) }
	fn upsert_prize_sku() -> Weight { Weight::from_parts(30_000, 0) }
	fn set_featured_rotation_config() -> Weight { Weight::from_parts(60_000, 0) }
	fn redeem_prize_with_tickets() -> Weight { Weight::from_parts(150_000, 0) }
	fn purchase_prize_with_native() -> Weight { Weight::from_parts(180_000, 0) }
	fn upsert_arcade_pack_credit_sku_v2() -> Weight { Weight::from_parts(50_000, 0) }
	fn redeem_arcade_pack_credit_with_tickets_v2() -> Weight { Weight::from_parts(300_000, 0) }
	fn rotate_featured() -> Weight { Weight::from_parts(150_000, 0) }
}

/// Weight functions for `pallet_eterra_economy`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraEconomy::Products` (r:1 w:1)
	/// Proof: `EterraEconomy::Products` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn create_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3581`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3581))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Products` (r:1 w:1)
	/// Proof: `EterraEconomy::Products` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn set_product_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3581`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3581))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Entitlements` (r:0 w:1)
	/// Proof: `EterraEconomy::Entitlements` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn grant_entitlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Entitlements` (r:0 w:1)
	/// Proof: `EterraEconomy::Entitlements` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn revoke_entitlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Credits` (r:1 w:1)
	/// Proof: `EterraEconomy::Credits` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn grant_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3565`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3565))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Credits` (r:1 w:1)
	/// Proof: `EterraEconomy::Credits` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn consume_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `168`
		//  Estimated: `3565`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3565))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::SponsorPools` (r:1 w:1)
	/// Proof: `EterraEconomy::SponsorPools` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn deposit_sponsor_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3505`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3505))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::RevenueEscrow` (r:1 w:1)
	/// Proof: `EterraEconomy::RevenueEscrow` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn record_revenue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3505`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3505))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraEconomy::Products` (r:1 w:0)
	/// Proof: `EterraEconomy::Products` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `EterraEconomy::FulfilledReceipts` (r:1 w:1)
	/// Proof: `EterraEconomy::FulfilledReceipts` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EterraEconomy::Credits` (r:1 w:1)
	/// Proof: `EterraEconomy::Credits` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `EterraEconomy::RevenueEscrow` (r:1 w:1)
	/// Proof: `EterraEconomy::RevenueEscrow` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `EterraEconomy::Entitlements` (r:0 w:1)
	/// Proof: `EterraEconomy::Entitlements` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn fulfill_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3581`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3581))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	fn claim_arcade_credit() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn set_ticket_asset() -> Weight {
		Weight::from_parts(20_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(2, 1))
	}
	fn set_ticket_reward_policy() -> Weight {
		Weight::from_parts(35_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 1))
	}
	fn set_arcade_economy_pause() -> Weight {
		Weight::from_parts(15_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}
	fn set_arcade_account_restriction() -> Weight {
		Weight::from_parts(15_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}
	fn transfer_tickets() -> Weight {
		Weight::from_parts(70_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(5, 2))
	}
	fn upsert_prize_sku() -> Weight {
		Weight::from_parts(30_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 1))
	}
	fn set_featured_rotation_config() -> Weight {
		Weight::from_parts(65_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(1, 1))
	}
	fn redeem_prize_with_tickets() -> Weight {
		Weight::from_parts(180_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(12, 9))
	}
	fn purchase_prize_with_native() -> Weight {
		Weight::from_parts(220_000_000, 0).saturating_add(T::DbWeight::get().reads_writes(14, 10))
	}
	/// Conservative pre-release bound. This includes validating the target
	/// PackSkuVersion through the configured Nexus V2 issuer.
	fn upsert_arcade_pack_credit_sku_v2() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8_192))
			.saturating_add(T::DbWeight::get().reads_writes(2, 1))
	}
	/// Conservative pre-release bound for the atomic Ticket burn, Pack Credit
	/// issuance, capacity accounting, and global replay receipt.
	fn redeem_arcade_pack_credit_with_tickets_v2() -> Weight {
		Weight::from_parts(300_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16_384))
			.saturating_add(T::DbWeight::get().reads_writes(18, 12))
	}
	/// Conservative upper bound for one bounded 12-slot rotation over the
	/// configured subject pool. Production activation still requires regenerating
	/// this file with the target release hardware benchmark profile.
	fn rotate_featured() -> Weight {
		Weight::from_parts(150_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8_192))
			.saturating_add(T::DbWeight::get().reads_writes(3, 3))
	}
}
