
//! Autogenerated weights for `pallet_eterra_faucet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_faucet
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-faucet/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_faucet`.
pub trait WeightInfo {
	fn claim() -> Weight;
}

impl WeightInfo for () {
	fn claim() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_faucet`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraFaucet::LastClaim` (r:1 w:1)
	/// Proof: `EterraFaucet::LastClaim` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EterraFaucet::FaucetAccount` (r:1 w:0)
	/// Proof: `EterraFaucet::FaucetAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EterraFaucet::PayoutAmount` (r:1 w:0)
	/// Proof: `EterraFaucet::PayoutAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `3614`
		// Minimum execution time: 776_000_000 picoseconds.
		Weight::from_parts(778_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3614))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
