
//! Autogenerated weights for `pallet_eterra_simple_tcg`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_simple_tcg
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-simple-tcg/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_simple_tcg`.
pub trait WeightInfo {
	fn mint_card() -> Weight;
	fn transfer_card() -> Weight;
	fn set_price() -> Weight;
	fn remove_price() -> Weight;
	fn buy_card() -> Weight;
}

impl WeightInfo for () {
	fn mint_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn transfer_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_price() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_price() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_simple_tcg`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::NextCardId` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::NextCardId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::OwnedCards` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::OwnedCards` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::Cards` (r:0 w:1)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	fn mint_card() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `5915`
		// Minimum execution time: 776_000_000 picoseconds.
		Weight::from_parts(1_103_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5915))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `EterraSimpleTCG::Cards` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::CardPrices` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::CardPrices` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::ListedByOwner` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::ListedByOwner` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::OwnedCards` (r:2 w:2)
	/// Proof: `EterraSimpleTCG::OwnedCards` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	fn transfer_card() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `332`
		//  Estimated: `10840`
		// Minimum execution time: 452_000_000 picoseconds.
		Weight::from_parts(564_000_000, 0)
			.saturating_add(Weight::from_parts(0, 10840))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `EterraSimpleTCG::Cards` (r:1 w:0)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::ListedByOwner` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::ListedByOwner` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::CardPrices` (r:0 w:1)
	/// Proof: `EterraSimpleTCG::CardPrices` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `5915`
		// Minimum execution time: 191_000_000 picoseconds.
		Weight::from_parts(222_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5915))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraSimpleTCG::Cards` (r:1 w:0)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::CardPrices` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::CardPrices` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::ListedByOwner` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::ListedByOwner` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	fn remove_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `290`
		//  Estimated: `5915`
		// Minimum execution time: 273_000_000 picoseconds.
		Weight::from_parts(314_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5915))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraSimpleTCG::CardPrices` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::CardPrices` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::Cards` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::ListedByOwner` (r:1 w:1)
	/// Proof: `EterraSimpleTCG::ListedByOwner` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::OwnedCards` (r:2 w:2)
	/// Proof: `EterraSimpleTCG::OwnedCards` (`max_values`: None, `max_size`: Some(2450), added: 4925, mode: `MaxEncodedLen`)
	fn buy_card() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `384`
		//  Estimated: `10840`
		// Minimum execution time: 1_043_000_000 picoseconds.
		Weight::from_parts(1_204_000_000, 0)
			.saturating_add(Weight::from_parts(0, 10840))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}
