[package]
name = "eterra-drand-quicknet"
description = "Pinned no-std verifier for drand Quicknet RFC 9380 beacons"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
bls12_381 = { workspace = true }
pairing = { workspace = true }
sha2-09 = { workspace = true }

[features]
default = ["std"]
std = []
