
//! Autogenerated weights for `pallet_eterra_authority`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-05-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-eterra-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_authority
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-authority/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_authority`.
pub trait WeightInfo {
	fn authorize_authority() -> Weight;
	fn set_authority_status() -> Weight;
	fn revoke_authority() -> Weight;
}

impl WeightInfo for () {
	fn authorize_authority() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_authority_status() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn revoke_authority() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_authority`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraAuthority::Authorities` (r:1 w:1)
	/// Proof: `EterraAuthority::Authorities` (`max_values`: None, `max_size`: Some(253), added: 2728, mode: `MaxEncodedLen`)
	/// Storage: `EterraAuthority::AuthorityByAccount` (r:0 w:1)
	/// Proof: `EterraAuthority::AuthorityByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn authorize_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `3718`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3718))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraAuthority::Authorities` (r:1 w:1)
	/// Proof: `EterraAuthority::Authorities` (`max_values`: None, `max_size`: Some(253), added: 2728, mode: `MaxEncodedLen`)
	fn set_authority_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3718`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3718))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraAuthority::Authorities` (r:1 w:1)
	/// Proof: `EterraAuthority::Authorities` (`max_values`: None, `max_size`: Some(253), added: 2728, mode: `MaxEncodedLen`)
	/// Storage: `EterraAuthority::AuthorityByAccount` (r:0 w:1)
	/// Proof: `EterraAuthority::AuthorityByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn revoke_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3718`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3718))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
