
//! Autogenerated weights for `pallet_eterra_game_authority`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_eterra_game_authority
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-game-authority/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_game_authority`.
pub trait WeightInfo {
	fn on_initialize(games_len: u32, removed_players: u32) -> Weight;
	fn add_server() -> Weight;
	fn remove_server() -> Weight;
	fn create_game() -> Weight;
	fn add_player() -> Weight;
	fn add_players_batch(n: u32) -> Weight;
	fn create_game_with_batch_add(n: u32) -> Weight;
	fn record_eliminations() -> Weight;
	fn end_game() -> Weight;
}

impl WeightInfo for () {
	fn on_initialize(_games_len: u32, _removed_players: u32) -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn add_server() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_server() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn create_game() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn add_player() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn add_players_batch(_n: u32) -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn create_game_with_batch_add(_n: u32) -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn record_eliminations() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn end_game() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_game_authority`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	fn on_initialize(games_len: u32, removed_players: u32) -> Weight {
		Weight::from_parts(0, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().reads(games_len as u64))
			.saturating_add(T::DbWeight::get().writes(games_len as u64))
			.saturating_add(T::DbWeight::get().writes(removed_players as u64))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:1)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `3513`
		// Minimum execution time: 145_000_000 picoseconds.
		Weight::from_parts(162_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:1)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `3513`
		// Minimum execution time: 168_000_000 picoseconds.
		Weight::from_parts(189_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::NextGameId` (r:1 w:1)
	/// Proof: `EterraGameAuthority::NextGameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Expirations` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Expirations` (`max_values`: None, `max_size`: Some(2070), added: 4545, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:0 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	fn create_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `5535`
		// Minimum execution time: 225_000_000 picoseconds.
		Weight::from_parts(237_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5535))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ActiveGameByPlayer` (r:1 w:1)
	/// Proof: `EterraGameAuthority::ActiveGameByPlayer` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn add_player() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `7621`
		// Minimum execution time: 243_000_000 picoseconds.
		Weight::from_parts(248_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ActiveGameByPlayer` (r:32 w:32)
	/// Proof: `EterraGameAuthority::ActiveGameByPlayer` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn add_players_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `7621 + n * (2531 ±0)`
		// Minimum execution time: 257_000_000 picoseconds.
		Weight::from_parts(268_157_608, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			// Standard Error: 2_114_264
			.saturating_add(Weight::from_parts(76_515_130, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::NextGameId` (r:1 w:1)
	/// Proof: `EterraGameAuthority::NextGameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Expirations` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Expirations` (`max_values`: None, `max_size`: Some(2070), added: 4545, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ActiveGameByPlayer` (r:32 w:32)
	/// Proof: `EterraGameAuthority::ActiveGameByPlayer` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:0 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn create_game_with_batch_add(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `5535 + n * (2531 ±0)`
		// Minimum execution time: 306_000_000 picoseconds.
		Weight::from_parts(119_098_438, 0)
			.saturating_add(Weight::from_parts(0, 5535))
			// Standard Error: 2_784_718
			.saturating_add(Weight::from_parts(94_390_484, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Eliminations` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Eliminations` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn record_eliminations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `7621`
		// Minimum execution time: 234_000_000 picoseconds.
		Weight::from_parts(237_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	fn end_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `7621`
		// Minimum execution time: 191_000_000 picoseconds.
		Weight::from_parts(194_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
