
//! Autogenerated weights for `pallet_eterra_game_authority`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-03-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-eterra-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_game_authority
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-game-authority/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_eterra_game_authority`.
pub trait WeightInfo {
	fn on_initialize(games_len: u32, removed_players: u32) -> Weight;
	fn add_server() -> Weight;
	fn remove_server() -> Weight;
	fn create_game_with_round_id(n: u32, ) -> Weight;
	fn end_game_with_command_id() -> Weight;
	fn record_eliminations_with_event_id() -> Weight;
}

/// Weight functions for `pallet_eterra_game_authority`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn on_initialize(games_len: u32, removed_players: u32) -> Weight {
		Weight::from_parts(0, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().reads(games_len as u64))
			.saturating_add(T::DbWeight::get().writes(games_len as u64))
			.saturating_add(T::DbWeight::get().writes(removed_players as u64))
	}

	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:1)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3513`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:1)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `3513`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::GameIdByRoundId` (r:1 w:1)
	/// Proof: `EterraGameAuthority::GameIdByRoundId` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::NextGameId` (r:1 w:1)
	/// Proof: `EterraGameAuthority::NextGameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Expirations` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Expirations` (`max_values`: None, `max_size`: Some(2070), added: 4545, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ActiveGameByPlayer` (r:32 w:32)
	/// Proof: `EterraGameAuthority::ActiveGameByPlayer` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:0 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn create_game_with_round_id(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `5535 + n * (2531 ±0)`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(17_888_768, 0)
			.saturating_add(Weight::from_parts(0, 5535))
			// Standard Error: 5_403
			.saturating_add(Weight::from_parts(5_223_422, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ProcessedEndCommands` (r:1 w:1)
	/// Proof: `EterraGameAuthority::ProcessedEndCommands` (`max_values`: None, `max_size`: Some(288), added: 2763, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ActiveGameByPlayer` (r:0 w:128)
	/// Proof: `EterraGameAuthority::ActiveGameByPlayer` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn end_game_with_command_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4271`
		//  Estimated: `7621`
		// Minimum execution time: 215_000_000 picoseconds.
		Weight::from_parts(217_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(130))
	}
	/// Storage: `EterraGameAuthority::WhitelistedServers` (r:1 w:0)
	/// Proof: `EterraGameAuthority::WhitelistedServers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::ProcessedEliminationEvents` (r:1 w:1)
	/// Proof: `EterraGameAuthority::ProcessedEliminationEvents` (`max_values`: None, `max_size`: Some(194), added: 2669, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Games` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Games` (`max_values`: None, `max_size`: Some(4156), added: 6631, mode: `MaxEncodedLen`)
	/// Storage: `EterraGameAuthority::Eliminations` (r:1 w:1)
	/// Proof: `EterraGameAuthority::Eliminations` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn record_eliminations_with_event_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206`
		//  Estimated: `7621`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	fn on_initialize(games_len: u32, removed_players: u32) -> Weight {
		Weight::from_parts(0, 0)
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(games_len as u64))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(games_len as u64))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(removed_players as u64))
	}

	fn add_server() -> Weight {
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(1))
	}

	fn remove_server() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(1))
	}

	fn create_game_with_round_id(n: u32, ) -> Weight {
		Weight::from_parts(17_888_768, 0)
			.saturating_add(Weight::from_parts(0, 5535))
			.saturating_add(Weight::from_parts(5_223_422, 0).saturating_mul(n.into()))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(4))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(4))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}

	fn end_game_with_command_id() -> Weight {
		Weight::from_parts(217_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(3))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(130))
	}

	fn record_eliminations_with_event_id() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7621))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(4))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(3))
	}
}
