
//! Autogenerated weights for `pallet_eterra_media`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_media
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-media/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_media`.
pub trait WeightInfo {
	fn create_collection() -> Weight;
	fn set_collection_role() -> Weight;
	fn register_media() -> Weight;
	fn freeze_collection() -> Weight;
	fn deprecate_media() -> Weight;
}

impl WeightInfo for () {
	fn create_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_collection_role() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn register_media() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn freeze_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn deprecate_media() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_media`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraMedia::NextCollectionId` (r:1 w:1)
	/// Proof: `EterraMedia::NextCollectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::CollectionRoles` (r:0 w:1)
	/// Proof: `EterraMedia::CollectionRoles` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::Collections` (r:0 w:1)
	/// Proof: `EterraMedia::Collections` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::CollectionDescriptions` (r:0 w:1)
	/// Proof: `EterraMedia::CollectionDescriptions` (`max_values`: None, `max_size`: Some(278), added: 2753, mode: `MaxEncodedLen`)
	fn create_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `43`
		//  Estimated: `1489`
		// Minimum execution time: 227_000_000 picoseconds.
		Weight::from_parts(799_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `EterraMedia::CollectionRoles` (r:2 w:1)
	/// Proof: `EterraMedia::CollectionRoles` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn set_collection_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `6094`
		// Minimum execution time: 201_000_000 picoseconds.
		Weight::from_parts(205_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6094))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraMedia::Collections` (r:1 w:0)
	/// Proof: `EterraMedia::Collections` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::CollectionRoles` (r:1 w:0)
	/// Proof: `EterraMedia::CollectionRoles` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::NextMediaId` (r:1 w:1)
	/// Proof: `EterraMedia::NextMediaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::Media` (r:0 w:1)
	/// Proof: `EterraMedia::Media` (`max_values`: None, `max_size`: Some(400), added: 2875, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::MediaOwner` (r:0 w:1)
	/// Proof: `EterraMedia::MediaOwner` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn register_media() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `3584`
		// Minimum execution time: 294_000_000 picoseconds.
		Weight::from_parts(299_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EterraMedia::Collections` (r:1 w:1)
	/// Proof: `EterraMedia::Collections` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::CollectionRoles` (r:1 w:0)
	/// Proof: `EterraMedia::CollectionRoles` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn freeze_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3584`
		// Minimum execution time: 184_000_000 picoseconds.
		Weight::from_parts(187_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3584))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraMedia::Media` (r:1 w:1)
	/// Proof: `EterraMedia::Media` (`max_values`: None, `max_size`: Some(400), added: 2875, mode: `MaxEncodedLen`)
	/// Storage: `EterraMedia::CollectionRoles` (r:1 w:0)
	/// Proof: `EterraMedia::CollectionRoles` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn deprecate_media() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `297`
		//  Estimated: `3865`
		// Minimum execution time: 183_000_000 picoseconds.
		Weight::from_parts(193_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3865))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
