
//! Autogenerated weights for `pallet_eterra_gamer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_gamer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-gamer/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_gamer`.
pub trait WeightInfo {
	fn set_gamer_tag() -> Weight;
	fn set_arcade_initials() -> Weight;
	fn set_avatar() -> Weight;
	fn grant_experience() -> Weight;
	fn redeem_levels() -> Weight;
	fn set_steam_link_authority() -> Weight;
	fn link_steam() -> Weight;
	fn unlink_steam() -> Weight;
	fn freeze_player() -> Weight;
	fn unfreeze_player() -> Weight;
	fn set_region() -> Weight;
}

impl WeightInfo for () {
	fn set_gamer_tag() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_arcade_initials() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_avatar() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn grant_experience() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn redeem_levels() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_steam_link_authority() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn link_steam() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unlink_steam() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn freeze_player() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unfreeze_player() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_region() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_gamer`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraGamer::GamerTag` (r:1 w:1)
	/// Proof: `EterraGamer::GamerTag` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_gamer_tag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250`
		//  Estimated: `3593`
		// Minimum execution time: 679_000_000 picoseconds.
		Weight::from_parts(697_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraGamer::ArcadeInitials` (r:1 w:1)
	/// Proof: `EterraGamer::ArcadeInitials` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_arcade_initials() -> Weight {
		Weight::from_parts(697_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraGamer::AvatarCid` (r:1 w:1)
	/// Proof: `EterraGamer::AvatarCid` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_avatar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250`
		//  Estimated: `3611`
		// Minimum execution time: 755_000_000 picoseconds.
		Weight::from_parts(764_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3611))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `EterraGamer::Experience` (r:1 w:1)
	/// Proof: `EterraGamer::Experience` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn grant_experience() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3529`
		// Minimum execution time: 111_000_000 picoseconds.
		Weight::from_parts(142_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3529))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraGamer::Level` (r:1 w:1)
	/// Proof: `EterraGamer::Level` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `EterraGamer::Experience` (r:1 w:1)
	/// Proof: `EterraGamer::Experience` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn redeem_levels() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203`
		//  Estimated: `3529`
		// Minimum execution time: 222_000_000 picoseconds.
		Weight::from_parts(235_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3529))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn set_steam_link_authority() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn link_steam() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unlink_steam() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn freeze_player() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unfreeze_player() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_region() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
