
//! Autogenerated weights for `pallet_eterra`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_eterra
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra`.
pub trait WeightInfo {
	fn create_game() -> Weight;
	fn play() -> Weight;
	fn submit_hand() -> Weight;
	fn play_from_hand() -> Weight;
	fn force_finish_turn() -> Weight;
	fn set_current_hand() -> Weight;
	fn set_preset_hand() -> Weight;
}

impl WeightInfo for () {
	fn create_game() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn play() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_hand() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn play_from_hand() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn force_finish_turn() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_current_hand() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_preset_hand() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Eterra::CurrentHandOf` (r:1 w:0)
	/// Proof: `Eterra::CurrentHandOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::ActiveGameOf` (r:1 w:1)
	/// Proof: `Eterra::ActiveGameOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::GameStorage` (r:1 w:1)
	/// Proof: `Eterra::GameStorage` (`max_values`: None, `max_size`: Some(237), added: 2712, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::PlayerGames` (r:2 w:2)
	/// Proof: `Eterra::PlayerGames` (`max_values`: None, `max_size`: Some(369), added: 2844, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::HandsOfGame` (r:1 w:1)
	/// Proof: `Eterra::HandsOfGame` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::GameModes` (r:0 w:1)
	/// Proof: `Eterra::GameModes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100`
		//  Estimated: `6678`
		// Minimum execution time: 703_000_000 picoseconds.
		Weight::from_parts(1_042_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6678))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Dev-only: play using a raw `Move` (mapped to `play_from_hand` weight).
	fn play() -> Weight {
		Self::play_from_hand()
	}
	/// Storage: `Eterra::GameStorage` (r:1 w:1)
	/// Proof: `Eterra::GameStorage` (`max_values`: None, `max_size`: Some(237), added: 2712, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::HandsOfGame` (r:2 w:2)
	/// Proof: `Eterra::HandsOfGame` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::CurrentHandOf` (r:1 w:0)
	/// Proof: `Eterra::CurrentHandOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EterraSimpleTCG::Cards` (r:5 w:0)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::GameModes` (r:1 w:0)
	/// Proof: `Eterra::GameModes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `EterraMonteCarloAi::Nonce` (r:1 w:1)
	/// Proof: `EterraMonteCarloAi::Nonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn submit_hand() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `855`
		//  Estimated: `14135`
		// Minimum execution time: 6_350_000_000 picoseconds.
		Weight::from_parts(9_020_000_000, 0)
			.saturating_add(Weight::from_parts(0, 14135))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Eterra::GameStorage` (r:1 w:1)
	/// Proof: `Eterra::GameStorage` (`max_values`: None, `max_size`: Some(237), added: 2712, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::HandsOfGame` (r:2 w:2)
	/// Proof: `Eterra::HandsOfGame` (`max_values`: None, `max_size`: Some(142), added: 2617, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::GameModes` (r:1 w:0)
	/// Proof: `Eterra::GameModes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `EterraMonteCarloAi::Nonce` (r:1 w:1)
	/// Proof: `EterraMonteCarloAi::Nonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn play_from_hand() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `523`
		//  Estimated: `6224`
		// Minimum execution time: 5_294_000_000 picoseconds.
		Weight::from_parts(6_774_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6224))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Eterra::GameStorage` (r:1 w:1)
	/// Proof: `Eterra::GameStorage` (`max_values`: None, `max_size`: Some(237), added: 2712, mode: `MaxEncodedLen`)
	fn force_finish_turn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `3702`
		// Minimum execution time: 376_000_000 picoseconds.
		Weight::from_parts(474_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3702))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraSimpleTCG::Cards` (r:5 w:0)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::CurrentHandOf` (r:0 w:1)
	/// Proof: `Eterra::CurrentHandOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn set_current_hand() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `514`
		//  Estimated: `14135`
		// Minimum execution time: 517_000_000 picoseconds.
		Weight::from_parts(596_000_000, 0)
			.saturating_add(Weight::from_parts(0, 14135))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraSimpleTCG::Cards` (r:5 w:0)
	/// Proof: `EterraSimpleTCG::Cards` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `Eterra::CurrentHandOf` (r:0 w:1)
	/// Proof: `Eterra::CurrentHandOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn set_preset_hand() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `508`
		//  Estimated: `14135`
		// Minimum execution time: 572_000_000 picoseconds.
		Weight::from_parts(653_000_000, 0)
			.saturating_add(Weight::from_parts(0, 14135))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
