//! Autogenerated weights for `pallet_eterra_tcg`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-03-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024
//!
//! Executed Command:
//! ./target/release/solochain-eterra-node benchmark pallet
//! --runtime ./target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
//! --genesis-builder=runtime --genesis-builder-preset=development
//! --pallet pallet_eterra_tcg --extrinsic * --steps 50 --repeat 20
//! --output pallets/eterra-tcg/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_tcg`.
pub trait WeightInfo {
	fn mint_pack() -> Weight;
	fn mint_pro() -> Weight;
	fn mint_card() -> Weight;
	fn claim_starter_grant() -> Weight;
	fn set_starter_team_config() -> Weight;
	fn generate_slot() -> Weight;
	fn spin_pro() -> Weight;
	fn accept_slot() -> Weight;
	fn accept_pro() -> Weight;
	fn transfer_card() -> Weight;
	fn set_price() -> Weight;
	fn remove_price() -> Weight;
	fn buy_card() -> Weight;
	fn create_season_collection() -> Weight;
	fn publish_season_collection() -> Weight;
	fn remove_season_collection() -> Weight;
	fn add_season_collection_asset() -> Weight;
	fn remove_season_collection_asset() -> Weight;
	fn move_season_collection_asset() -> Weight;
	fn set_season_collection_asset_weights() -> Weight;
	fn buy_card_capacity() -> Weight;
	fn init_card_nft_collection() -> Weight;
	fn convert_to_nft() -> Weight;
	fn unwrap_from_nft() -> Weight;
	fn set_progression_tree() -> Weight;
	fn assign_progression_tree_to_card() -> Weight;
	fn grant_card_experience() -> Weight;
	fn forge_progression_node() -> Weight;
	fn set_card_magic_loadout(spells: u32) -> Weight;
	fn seed_alpha_progression_gear() -> Weight;
	fn seed_alpha_spell() -> Weight;
	fn publish_v2_catalog() -> Weight;
	fn publish_v2_pool() -> Weight;
	fn publish_v2_pack_sku() -> Weight;
	fn issue_v2_training_credit() -> Weight;
	fn request_v2_pack_open() -> Weight;
	fn finalize_v2_pack_open() -> Weight;
	fn timeout_v2_pack_open() -> Weight;
	fn publish_v2_format() -> Weight;
	fn save_v2_team() -> Weight;
	fn set_v2_feature() -> Weight;
	fn request_v2_conversion() -> Weight;
	fn finalize_v2_conversion() -> Weight;
	fn timeout_v2_conversion() -> Weight;
	fn configure_v2_ascension() -> Weight;
	fn link_v2_season_eligibility() -> Weight;
	fn record_v2_ascension_progress() -> Weight;
	fn execute_v2_ascension() -> Weight;
	fn complete_v16_migration() -> Weight;
	fn transfer_wrapped_nft_v16() -> Weight;
}

impl WeightInfo for () {
		fn mint_pack() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn mint_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn mint_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn claim_starter_grant() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_starter_team_config() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn generate_slot() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn spin_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_slot() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn transfer_card() -> Weight {
		Weight::from_parts(1_200_000_000_000, 2_097_152)
	}
	fn set_price() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_price() -> Weight {
		Weight::from_parts(200_000_000_000, 524_288)
	}
	fn buy_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn create_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn publish_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn add_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn move_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_season_collection_asset_weights() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_card_capacity() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn init_card_nft_collection() -> Weight {
		// Conservative private-alpha bound until the V16 benchmark artifact is frozen.
		Weight::from_parts(50_000_000_000, 65_536)
	}
	fn convert_to_nft() -> Weight {
		// Includes NFT minting plus worst-case listing/index/sidecar mutation.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
	}
	fn unwrap_from_nft() -> Weight {
		// Includes NFT burn plus worst-case custody/index/sidecar mutation.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
	}
	fn set_progression_tree() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn assign_progression_tree_to_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn grant_card_experience() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn forge_progression_node() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_card_magic_loadout(spells: u32) -> Weight {
		Weight::from_parts(50_000_000_000, 65_536)
			.saturating_add(Weight::from_parts(1_000_000, 32).saturating_mul(spells.into()))
	}
	fn seed_alpha_progression_gear() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn seed_alpha_spell() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn publish_v2_catalog() -> Weight {
		Weight::from_parts(25_000_000, 0)
	}
	fn publish_v2_pool() -> Weight {
		Weight::from_parts(75_000_000, 0)
	}
	fn publish_v2_pack_sku() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn issue_v2_training_credit() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
	fn request_v2_pack_open() -> Weight {
		Weight::from_parts(250_000_000, 0)
	}
	fn finalize_v2_pack_open() -> Weight {
		Weight::from_parts(900_000_000_000, 16_777_216)
	}
	fn timeout_v2_pack_open() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn publish_v2_format() -> Weight {
		Weight::from_parts(25_000_000, 0)
	}
	fn save_v2_team() -> Weight {
		Weight::from_parts(175_000_000, 0)
	}
	fn set_v2_feature() -> Weight {
		Weight::from_parts(15_000_000, 0)
	}
	fn request_v2_conversion() -> Weight {
		Weight::from_parts(225_000_000, 0)
	}
	fn finalize_v2_conversion() -> Weight {
		Weight::from_parts(130_000_000, 0)
	}
	fn timeout_v2_conversion() -> Weight {
		Weight::from_parts(120_000_000, 0)
	}
	fn configure_v2_ascension() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn link_v2_season_eligibility() -> Weight {
		Weight::from_parts(25_000_000, 0)
	}
	fn record_v2_ascension_progress() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn execute_v2_ascension() -> Weight {
		Weight::from_parts(200_000_000, 0)
	}
	fn complete_v16_migration() -> Weight {
		Weight::from_parts(35_000_000, 8_000)
	}
	fn transfer_wrapped_nft_v16() -> Weight {
		Weight::from_parts(150_000_000_000, 131_072)
	}
}

/// Weight functions for `pallet_eterra_tcg`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Proof: `EterraTCG::NextCardId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:0 w:6)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackCardInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackCardInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:0 w:1)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn mint_pack() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `7611`
		// Minimum execution time: 88_000_000 picoseconds.
			Weight::from_parts(95_000_000, 0)
				.saturating_add(Weight::from_parts(0, 7611))
				.saturating_add(T::DbWeight::get().reads(6))
				.saturating_add(T::DbWeight::get().writes(21))
		}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Proof: `EterraTCG::NextCardId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:0 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
		fn mint_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `7611`
		// Minimum execution time: 51_000_000 picoseconds.
			Weight::from_parts(52_000_000, 0)
				.saturating_add(Weight::from_parts(0, 7611))
				.saturating_add(T::DbWeight::get().reads(6))
				.saturating_add(T::DbWeight::get().writes(8))
		}

	/// Storage: `System::Account` (r:1 w:1)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Storage: `EterraTCG::Cards` (r:0 w:1)
		fn mint_card() -> Weight {
			Weight::from_parts(45_000_000, 0)
				.saturating_add(T::DbWeight::get().reads(5))
				.saturating_add(T::DbWeight::get().writes(7))
		}

	fn claim_starter_grant() -> Weight {
		Weight::from_parts(75_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(20))
			.saturating_add(T::DbWeight::get().writes(35))
	}

	fn set_starter_team_config() -> Weight {
		Weight::from_parts(15_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:1 w:0)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:1 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn generate_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `4224`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4224))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:1 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn spin_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `265`
		//  Estimated: `3523`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(29_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3523))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:1 w:1)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:2 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackCardInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackCardInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:0 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn accept_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `626`
		//  Estimated: `6056`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6056))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:0 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn accept_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `3523`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3523))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:2 w:2)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	fn transfer_card() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `485`
		//  Estimated: `14232`
		// Minimum execution time: 22_000_000 picoseconds.
		// Runtime MaxOwnedCards is 100,000, so each source/destination owner
		// index may encode about 400 KiB. Charge the legal codec maximum rather
		// than the historical 1,024-card benchmark fixture.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
			.saturating_add(T::DbWeight::get().reads(20))
			.saturating_add(T::DbWeight::get().writes(20))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:0)
	/// Storage: `EterraTCG::CardPrices` (r:0 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	fn set_price() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:0)
	/// Storage: `EterraTCG::CardPrices` (r:1 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	fn remove_price() -> Weight {
		Weight::from_parts(200_000_000_000, 524_288)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}

	/// Storage: `EterraTCG::CardPrices` (r:1 w:1)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	/// Storage: `EterraTCG::CardsByOwner` (r:2 w:2)
	/// Storage: `System::Account` (r:1 w:1)
	fn buy_card() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}

	fn create_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	fn publish_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn remove_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn add_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn remove_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn move_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn set_season_collection_asset_weights() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn buy_card_capacity() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn init_card_nft_collection() -> Weight {
		// Provisional conservative bound. Replace with the frozen V16 hardware
		// benchmark before any production activation.
		Weight::from_parts(50_000_000_000, 65_536)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(12))
	}

	fn convert_to_nft() -> Weight {
		// Covers NFT minting and the worst-case listed-card, owner-index,
		// custody-sidecar and account mutation path.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
			.saturating_add(T::DbWeight::get().reads(30))
			.saturating_add(T::DbWeight::get().writes(30))
	}

	fn unwrap_from_nft() -> Weight {
		// Covers NFT burn and the worst-case owner-index/custody-sidecar
		// restoration path.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
			.saturating_add(T::DbWeight::get().reads(30))
			.saturating_add(T::DbWeight::get().writes(30))
	}

	fn set_progression_tree() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn assign_progression_tree_to_card() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn grant_card_experience() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn forge_progression_node() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	fn set_card_magic_loadout(spells: u32) -> Weight {
		// `spells` remains a legacy Vec for SCALE compatibility. Charge the
		// decoded length so an oversized, ultimately rejected payload cannot
		// receive the old constant fee.
		Weight::from_parts(50_000_000_000, 65_536)
			.saturating_add(Weight::from_parts(1_000_000, 32).saturating_mul(spells.into()))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn seed_alpha_progression_gear() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn seed_alpha_spell() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn publish_v2_catalog() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}

	fn publish_v2_pool() -> Weight {
		Weight::from_parts(75_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(640))
			.saturating_add(T::DbWeight::get().writes(800))
	}

	fn publish_v2_pack_sku() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn issue_v2_training_credit() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	fn request_v2_pack_open() -> Weight {
		// Tutorial-credit readiness scans as many as 400 profiles twice:
		// once for eligible conversion profiles and again across subject and
		// creature activation state. Charge the configured maximum, not the
		// single-subject benchmark fixture.
		Weight::from_parts(500_000_000_000, 16_777_216)
			.saturating_add(T::DbWeight::get().reads(4_000))
			.saturating_add(T::DbWeight::get().writes(16))
	}

	fn finalize_v2_pack_open() -> Weight {
		// Worst-case configured pool selection for six cards scans 400
		// profiles and up to 256 poses per slot, plus subject/cosmetic
		// eligibility and novelty indexes. The single-subject benchmark fixture
		// does not cover those maxima, so private alpha uses a conservative
		// end-to-end bound pending regenerated production weights.
		Weight::from_parts(900_000_000_000, 16_777_216)
			.saturating_add(T::DbWeight::get().reads(5_500))
			.saturating_add(T::DbWeight::get().writes(128))
	}

	fn timeout_v2_pack_open() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
	}

	fn publish_v2_format() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn save_v2_team() -> Weight {
		Weight::from_parts(175_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(45))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn set_v2_feature() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn complete_v16_migration() -> Weight {
		Weight::from_parts(35_000_000, 8_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn transfer_wrapped_nft_v16() -> Weight {
		// Includes pallet-nfts ownership/account/config mutation plus repaired
		// owner and Nexus index transitions. Runtime MaxOwnedCards is 100,000,
		// so both owner-side indexes are charged at their legal codec maximum.
		Weight::from_parts(1_200_000_000_000, 2_097_152)
			.saturating_add(T::DbWeight::get().reads(24))
			.saturating_add(T::DbWeight::get().writes(18))
	}

	fn request_v2_conversion() -> Weight {
		Weight::from_parts(225_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(61))
			.saturating_add(T::DbWeight::get().writes(10))
	}

	fn finalize_v2_conversion() -> Weight {
		Weight::from_parts(130_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(12))
	}

	fn timeout_v2_conversion() -> Weight {
		Weight::from_parts(120_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(12))
	}

	fn configure_v2_ascension() -> Weight {
		Weight::from_parts(50_000_000, 8_000)
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn link_v2_season_eligibility() -> Weight {
		Weight::from_parts(25_000_000, 4_000)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn record_v2_ascension_progress() -> Weight {
		Weight::from_parts(50_000_000, 8_000)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}

	fn execute_v2_ascension() -> Weight {
		Weight::from_parts(200_000_000, 16_000)
			.saturating_add(T::DbWeight::get().reads(32))
			.saturating_add(T::DbWeight::get().writes(24))
	}
}
