//! Autogenerated weights for `pallet_eterra_tcg`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-03-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024
//!
//! Executed Command:
//! ./target/release/solochain-eterra-node benchmark pallet
//! --runtime ./target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
//! --genesis-builder=runtime --genesis-builder-preset=development
//! --pallet pallet_eterra_tcg --extrinsic * --steps 50 --repeat 20
//! --output pallets/eterra-tcg/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_tcg`.
pub trait WeightInfo {
	fn mint_pack() -> Weight;
	fn mint_pro() -> Weight;
	fn mint_card() -> Weight;
	fn generate_slot() -> Weight;
	fn spin_pro() -> Weight;
	fn accept_slot() -> Weight;
	fn accept_pro() -> Weight;
	fn transfer_card() -> Weight;
	fn set_price() -> Weight;
	fn remove_price() -> Weight;
	fn buy_card() -> Weight;
	fn create_season_collection() -> Weight;
	fn publish_season_collection() -> Weight;
	fn remove_season_collection() -> Weight;
	fn add_season_collection_asset() -> Weight;
	fn remove_season_collection_asset() -> Weight;
	fn move_season_collection_asset() -> Weight;
	fn buy_card_capacity() -> Weight;
	fn init_card_nft_collection() -> Weight;
	fn convert_to_nft() -> Weight;
	fn unwrap_from_nft() -> Weight;
}

impl WeightInfo for () {
		fn mint_pack() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn mint_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn mint_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn generate_slot() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn spin_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_slot() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_pro() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn transfer_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_price() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_price() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_card() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn create_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn publish_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_season_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn add_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn remove_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn move_season_collection_asset() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_card_capacity() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn init_card_nft_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn convert_to_nft() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unwrap_from_nft() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_tcg`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Proof: `EterraTCG::NextCardId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:0 w:6)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackCardInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackCardInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:0 w:1)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn mint_pack() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `7611`
		// Minimum execution time: 88_000_000 picoseconds.
			Weight::from_parts(95_000_000, 0)
				.saturating_add(Weight::from_parts(0, 7611))
				.saturating_add(T::DbWeight::get().reads(6))
				.saturating_add(T::DbWeight::get().writes(21))
		}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Proof: `EterraTCG::NextCardId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:0 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
		fn mint_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `7611`
		// Minimum execution time: 51_000_000 picoseconds.
			Weight::from_parts(52_000_000, 0)
				.saturating_add(Weight::from_parts(0, 7611))
				.saturating_add(T::DbWeight::get().reads(6))
				.saturating_add(T::DbWeight::get().writes(8))
		}

	/// Storage: `System::Account` (r:1 w:1)
	/// Storage: `EterraTCG::NextCardId` (r:1 w:1)
	/// Storage: `EterraTCG::CardsByOwner` (r:1 w:1)
	/// Storage: `EterraTCG::Cards` (r:0 w:1)
		fn mint_card() -> Weight {
			Weight::from_parts(45_000_000, 0)
				.saturating_add(T::DbWeight::get().reads(5))
				.saturating_add(T::DbWeight::get().writes(7))
		}

	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:1 w:0)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:1 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn generate_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `4224`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4224))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:1 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn spin_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `265`
		//  Estimated: `3523`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(29_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3523))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::PlayerPacks` (r:1 w:1)
	/// Proof: `EterraTCG::PlayerPacks` (`max_values`: None, `max_size`: Some(759), added: 3234, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::ActiveCard` (r:1 w:1)
	/// Proof: `EterraTCG::ActiveCard` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:2 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::PackCardInProgress` (r:0 w:1)
	/// Proof: `EterraTCG::PackCardInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:0 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn accept_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `626`
		//  Estimated: `6056`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6056))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}

	/// Storage: `EterraTCG::ProInProgress` (r:1 w:1)
	/// Proof: `EterraTCG::ProInProgress` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardAttempts` (r:0 w:1)
	/// Proof: `EterraTCG::CardAttempts` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn accept_pro() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `3523`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3523))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Proof: `EterraTCG::Cards` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `EterraTCG::CardsByOwner` (r:2 w:2)
	/// Proof: `EterraTCG::CardsByOwner` (`max_values`: None, `max_size`: Some(4146), added: 6621, mode: `MaxEncodedLen`)
	fn transfer_card() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `485`
		//  Estimated: `14232`
		// Minimum execution time: 22_000_000 picoseconds.
		Weight::from_parts(23_000_000, 0)
			.saturating_add(Weight::from_parts(0, 14232))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:0)
	/// Storage: `EterraTCG::CardPrices` (r:0 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	fn set_price() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `EterraTCG::Cards` (r:1 w:0)
	/// Storage: `EterraTCG::CardPrices` (r:1 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	fn remove_price() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `EterraTCG::CardPrices` (r:1 w:1)
	/// Storage: `EterraTCG::Cards` (r:1 w:1)
	/// Storage: `EterraTCG::ListedByOwner` (r:1 w:1)
	/// Storage: `EterraTCG::CardsByOwner` (r:2 w:2)
	/// Storage: `System::Account` (r:1 w:1)
	fn buy_card() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}

	fn create_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	fn publish_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn remove_season_collection() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn add_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn remove_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn move_season_collection_asset() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn buy_card_capacity() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn init_card_nft_collection() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn convert_to_nft() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn unwrap_from_nft() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
