
//! Autogenerated weights for `pallet_eterra_daily_slots`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookAir`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/solochain-eterra-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-eterra-runtime/solochain_eterra_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_eterra_daily_slots
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/eterra-daily-slots/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_eterra_daily_slots`.
pub trait WeightInfo {
	fn roll() -> Weight;
	fn set_reel_weights() -> Weight;
	fn set_all_reel_weights() -> Weight;
}

impl WeightInfo for () {
	fn roll() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_reel_weights() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn set_all_reel_weights() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Weight functions for `pallet_eterra_daily_slots`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `EterraDailySlots::RollsThisWindow` (r:1 w:1)
	/// Proof: `EterraDailySlots::RollsThisWindow` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EterraDailySlots::ReelWeights` (r:3 w:0)
	/// Proof: `EterraDailySlots::ReelWeights` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EterraDailySlots::RollHistory` (r:1 w:1)
	/// Proof: `EterraDailySlots::RollHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EterraDailySlots::LastRollTime` (r:0 w:1)
	/// Proof: `EterraDailySlots::LastRollTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn roll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `8632`
		// Minimum execution time: 498_000_000 picoseconds.
		Weight::from_parts(518_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8632))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EterraDailySlots::ReelWeights` (r:0 w:1)
	/// Proof: `EterraDailySlots::ReelWeights` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_reel_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(69_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EterraDailySlots::ReelWeights` (r:0 w:3)
	/// Proof: `EterraDailySlots::ReelWeights` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_all_reel_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 133_000_000 picoseconds.
		Weight::from_parts(136_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
