[package]
name = "pallet-eterra-gamer"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
eterra-nexus-primitives = { workspace = true }
scale-info         = { workspace = true, features = ["derive"] }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }

sp-std             = { workspace = true }
sp-runtime         = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true, default-features = false }

frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-alpha-access = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-system-benchmarking = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
sp-io = { workspace = true, default-features = false }
sp-keystore = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
  "eterra-nexus-primitives/std",
  "scale-info/std",
  "parity-scale-codec/std",
  "sp-std/std",
  "sp-runtime/std",
  "sp-core/std",
  "sp-io/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-balances/std",
  "pallet-alpha-access/std",
  "frame-benchmarking?/std",
  "frame-system-benchmarking?/std",
]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-alpha-access/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
